IMAGE_NAME=Fedora-Cloud-Base-20141203-21.x86_64

RAW_IMAGES_DIR=~/images
BACKING_IMAGES_DIR=~/backing-images

RAW=$RAW_IMAGES_DIR/$IMAGE_NAME.qcow2
INSTANCE_NAME=test-$IMAGE_NAME
BACKING_FILE=$BACKING_IMAGES_DIR/$INSTANCE_NAME.qcow2

CLOUDINIT_ISO=/tmp/seed.iso

RAM=2048
