VIRSH_URL=qemu:///system

RAW_IMAGES_DIR=~/images
BACKING_IMAGES_DIR=~/backing-images
CLOUDINIT_ISO_DIR=~/cloudinit

IMAGE_NAME=Fedora-Cloud-Base-22-20150521.x86_64
RAW=$RAW_IMAGES_DIR/$IMAGE_NAME.qcow2

INSTANCE_NAME=test-$IMAGE_NAME
BACKING_FILE=$BACKING_IMAGES_DIR/$INSTANCE_NAME.qcow2

CLOUDINIT_ISO_SRC_DIR=cloudinit-src/arothste-cloudadmin
CLOUDINIT_ISO=$CLOUDINIT_ISO_DIR/$INSTANCE_NAME-cloudinit.iso

RAM=2048
